### ISSUE TITLE
Support hash-based config of ignoreVariables and ignoreFunctions

### ISSUE THREAD

**Issue by bmagnantb** [AndyOGo/stylelint-declaration-strict-value#107]
I'm trying to set up a configuration that allows variables for some properties, but only functions for others, but it seems only `ignoreValues` supports hash-based config, while `ignoreVariables` and `ignoreFunctions` always apply to all properties.

Example:
I'd like to allow variables for `/color/` but disable them for `transition`
```
'scale-unlimited/declaration-strict-value': [
  [ '/color/', 'transition' ],
  {
    ignoreValues: {
      '/color/': [ 'transparent' ]
    },
    ignoreVariables: {
      'transition': false
    }
  }
],
```

**Comment by AndyOGo** [comment]
Basic support is released with [`v1.6.0`](https://www.npmjs.com/package/stylelint-declaration-strict-value/v/1.6.0).
Limitation: deviating regexes for primary and secondary options aren't supported, see #109
