### ISSUE TITLE
TypeError: D is not a function

### ISSUE THREAD

**Issue by FDiskas** [AndyOGo/stylelint-declaration-strict-value#149]
stylelint-declaration-strict-value@1.7.9
stylelint@13.11.0

command:
```bash
stylelint 'src/**/*.{scss,css}' --fix
```

main.module.scss
```scss
body {
    color: red;
}
```
```bash
TypeError: D is not a function
    at /***/src/pages/main.module.scss:2:5
    at i (/***/node_modules/stylelint-declaration-strict-value/dist/index.js:1:6010)
```

.stylelintrc.json
```json
{
  "extends": ["stylelint-config-standard", "stylelint-prettier/recommended"],
  "plugins": ["stylelint-scss", "stylelint-declaration-strict-value", "stylelint-prettier"],
  "rules": {
    "prettier/prettier": true,
    "scss/at-extend-no-missing-placeholder": true,
    "unicode-bom": "never",
    "selector-class-pattern": "^[a-z][a-zA-Z0-9]+$",
    "max-nesting-depth": 4,
    "selector-max-compound-selectors": 4,
    "declaration-no-important": true,
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": ["tailwind", "apply", "variants", "responsive", "screen", "layer"]
      }
    ],
    "declaration-block-trailing-semicolon": null,
    "no-descending-specificity": null,
    "scale-unlimited/declaration-strict-value": "/color$/"
  }
}
```

By looking at bundled source code D function is used before it was defined. What a real function is behind that is unknown for me

**Comment by AndyOGo** [comment]
Thanks for your issue.

At first glimpse it looks to be related to the `--fix` option.
If you want autofixing, you need to implement the autofix rule.
https://github.com/AndyOGo/stylelint-declaration-strict-value#autofix-support

You can also disabled autifix on plugin basis with `disableFix`.
https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md#the-anatomy-of-a-plugin

Please let me know if that solves your issue.

**Comment by AndyOGo** [comment]
`D` was obfuscated from `autoFixFuncNormalized` function.

https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/8ab9bb3219ef4e36d6a87b5f2c47caad5ab91b26/src/index.ts#L431-L451
