### ISSUE TITLE
Plugin throws error for multiline variables

### ISSUE THREAD

**Issue by dawidk92** [AndyOGo/stylelint-declaration-strict-value#16]
border-color:
          $form-input-border-color
          $form-input-border-color
          $form-input-border-color
          $color-denim--light;

Throws:
Expected variable, function or keyword for "$form-input-border-color           $form-input-border-color           $form-input-border-color           $color-denim--light" of "border-color"   scale-unlimited/declaration-strict-value

**Comment by AndyOGo** [comment]
@dawidk92 
Thanks for your feedback. Please read the docs carefully.
Property shorthands are not support as of now.

Will close, since this issue is related to #11
