### ISSUE TITLE
Support for stylelint 14

### ISSUE THREAD

**Issue by anoopsinghbayes** [AndyOGo/stylelint-declaration-strict-value#205]
i was looking at migration guide for stylelint 14
and found this 

while reading through it i found this
![image](https://user-images.githubusercontent.com/6286517/153045666-40f41ba0-7d72-4901-8344-9887d852fbc4.png)

looks like you would need to add postcss-scss as dependency 
to do something like this
	[customSyntax: require('postcss-scss'),](https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/82d51c399ddaa2f9d282e419399dd2028f47830c/index.js#L5)

**Comment by AndyOGo** [comment]
Thank you for taking a look into that.

This plugin is using custom matchers for CSS-like syntaxes and does not rely on stylelint for that.
Ideally the user configures the syntax he is using without that plugin knowing anything about it.

**Comment by AndyOGo** [comment]
@anoopsinghbayes I just double checked.

And I merged a PR #198 for this last November already.

Is there any problem?

**Comment by anoopsinghbayes** [comment]
if i dont do this in the stylint config 

  `customSyntax: require('postcss-scss'),`
  
  i get the following warning 
  ` When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option`

**Comment by AndyOGo** [comment]
@anoopsinghbayes 
Of course you need too install that.

Please double check the migration guidelines for **users**, these do not apply to plugin authors.
https://stylelint.io/migration-guide/to-14#users

All required migrations for plugin authors are addressed in #198 
https://stylelint.io/migration-guide/to-14#plugin-authors
