### ISSUE TITLE
Is it possible to add a custom message?

### ISSUE THREAD

**Issue by chris-pearce** [AndyOGo/stylelint-declaration-strict-value#21]
Great plugin!

It doesn't seem possible to be able to add a [custom message](https://stylelint.io/user-guide/configuration/#custom-messages). This would be really nice to have.

**Comment by AndyOGo** [comment]
Thanks, very interesting idea.
Well I haven't incorporated special handling of either [custom messages](https://stylelint.io/user-guide/configuration/#custom-messages) nor [custom formatting](https://stylelint.io/developer-guide/formatters/)

**Comment by AndyOGo** [comment]
@chris-pearce 
I just released support for custom messages.
Hope this serves your needs well.

Readme is update here:
https://github.com/AndyOGo/stylelint-declaration-strict-value#message
