### ISSUE TITLE
ignoreKeywords default doesn’t seem to work

### ISSUE THREAD

**Issue by setek** [AndyOGo/stylelint-declaration-strict-value#24]
Not 100% sure if my implementation isn’t correct, but going by the docs it seems to be.

`'scale-unlimited/declaration-strict-value': [`
`            ['/color/', 'z-index'],`
`            {`
`                ignoreKeywords: {`
`                    '': ['inherit', 'initial', 'unset'],`
`                    '/color/': ['currentColor', 'transparent'],`
`                    'z-index': ['0', 'auto']`
`                },`
`            },`
`        ],`

I get the error:

`Expected variable, function or keyword for "inherit" of "color"          scale-unlimited/declaration-strict-value`

Am I doing something wrong?

Thanks

**Comment by AndyOGo** [comment]
By using a property hash you are defining your rules explicitly separate for each property, in your case `color` allows only `currentColor` and `transparent`.
The empty `''` string rule is used for any other property you haven't defined explicitly as default.
Hence it does neither match for `color` nor `z-index`.
Just add `inherit` to your `color` rules.

Here are the docs in question:
> This configuration can either be a simple "string", an [array] of "strings" or a complex hash of property/keyword mappings.
https://github.com/AndyOGo/stylelint-declaration-strict-value#ignorekeywords

> The basic principle works the same as above - you either have one keyword or a list of keywords. This time you can define them for each property separately, like:
...
**Note** In case you still want to define a default list of allowed keywords, you can with the empty `""` string property name, like:
https://github.com/AndyOGo/stylelint-declaration-strict-value#complex-mighty-hash-mapping
