### ISSUE TITLE
add regex to ignoreKeywords or allow scss functions with ignoreFunctions

### ISSUE THREAD

**Issue by di5abled** [AndyOGo/stylelint-declaration-strict-value#25]
Hello, very neat plugin, love it!

I'm using it in our codebase where we work with .scss files.
We have a function to get consistent values for margin/padding which is called `spacing('...')`.

So my configuration looks like:
```
"scale-unlimited/declaration-strict-value": [
            [
                "/margin/",
                "/padding/"
            ], {
                ignoreKeywords: ["0", "auto", "spacing"]
            }
        ],
```

But the following code is still considered as wrong:
`margin: spacing() 0;`

Am I missing out on something or is this currently not possible?

**Comment by AndyOGo** [comment]
Hello, thanks for your issue.

For functions you can use [`ignorefunctions`](https://github.com/AndyOGo/stylelint-declaration-strict-value#ignorefunctions).
Though be aware that the whole plugin only works for single properties like, `margin-top` and not for shorthand-syntax like `margin`.
Support for short hand syntax is tracked here #11

**Comment by di5abled** [comment]
seems like my remaining issues are also related to #11
