### ISSUE TITLE
Autofix should support error if not handled

### ISSUE THREAD

**Issue by devTeaa** [AndyOGo/stylelint-declaration-strict-value#251]
Hi currently if I create a autofix func and doesn't handle a value (for ex: `color: blue`), I would like to have an option to throw error that the value `blue` is not fixable from the function, I have tried implementing one here #250, sorry for not raising issue beforehand

reference:
* https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/master/test/auto-fix-func.js
* https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/master/test/helpers/auto-fix-func.js

**Comment by AndyOGo** [comment]
@devTeaa 
Thank you very much for the issue.
It's released with [`v1.9.0`](https://github.com/AndyOGo/stylelint-declaration-strict-value/releases/tag/v1.9.0)

**Comment by devTeaa** [comment]
Thanks a lot @AndyOGo
