### ISSUE TITLE
Support stylelint 15

### ISSUE THREAD

**Issue by silverwind** [AndyOGo/stylelint-declaration-strict-value#309]
[stylelint 15](https://github.com/stylelint/stylelint/releases/tag/15.0.0) is released, please update the range in `peerDependencies` if the plugin is compatible.

**Comment by AndyOGo** [comment]
Huh, that was much more to migrate than I expected.

Released in [`v1.9.2`](https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/master/CHANGELOG.md#192-2023-02-16).
