### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by siddharth-badola** [AndyOGo/stylelint-declaration-strict-value#323]
The project make use for stylelint v^15.1.0.  but the peerDependencies mentioned for stylelint is ">=7 <=15".
Trying to install this using npm results in error

npm : v8.8.0
node : v18.1.0

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: casino-lobby@0.0.0
npm ERR! Found: stylelint@15.6.1
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"^15.6.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@">=7 <=14" from stylelint-declaration-strict-value@1.9.1
npm ERR! node_modules/stylelint-declaration-strict-value
npm ERR!   dev stylelint-declaration-strict-value@"^1.9.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-05-05T13_02_26_778Z-debug-0.log`

Note : We can choose to force install it using --force options with npm i

**Comment by AndyOGo** [comment]
Hmh.
May you try to upgrade version 1.9.2.

it seems you are on 1.9.1.

> npm ERR! peer stylelint@">=7 <=14" from stylelint-declaration-strict-value@1.9.1

**Comment by siddharth-badola** [comment]
ahh :flushed:, seems like that was the issue, updating it to v1.9.2 fixed it.

Btw it's an amazing plugin, I have been using this for my codebase and I just love it :heart:
