### ISSUE TITLE
No validation when rgb/rgba/hsl colors are used

### ISSUE THREAD

**Issue by acherkashin** [AndyOGo/stylelint-declaration-strict-value#325]
I use the following stylelint configuration

```js
module.exports = {
  plugins: ['stylelint-declaration-strict-value'],
  files: ['**/*.css'],
  rules: {
    'scale-unlimited/declaration-strict-value': [
      ['color', 'background-color', 'font-size', 'font-weight', 'font-family', 'border-color'],
      {
        ignoreValues: ['currentColor', 'unset', 'inherit', 'initial', 'transparent'],
      },
    ],
  },
};
```

Everything works fine, for hex colors, font-weight, font-size and so on.

But when I use rgb/rgba/hsl functions to set up color, I don't see any validations.

<img width="610" alt="image" src="https://github.com/AndyOGo/stylelint-declaration-strict-value/assets/9947582/b5abd8ec-c2dd-4670-a7f2-abfda6b348ec">

**Comment by AndyOGo** [comment]
@acherkashin 
Please try to configure [`ignoreFunctions`](https://github.com/AndyOGo/stylelint-declaration-strict-value#ignorefunctions)

**Comment by acherkashin** [comment]
@AndyOGo 

I set up `ignoreFunctions` to `false` and now it works.

<img width="425" alt="image" src="https://github.com/AndyOGo/stylelint-declaration-strict-value/assets/9947582/aa308dd3-cf34-46dc-8abf-d70f06a78372">

<img width="479" alt="image" src="https://github.com/AndyOGo/stylelint-declaration-strict-value/assets/9947582/66e467ea-e355-4da0-818f-674e117184ea">

But when I use variable inside `drop-shadow` function, I still have validation.

<img width="560" alt="image" src="https://github.com/AndyOGo/stylelint-declaration-strict-value/assets/9947582/bdfe4123-f043-40e6-86fc-800c11564775">

I understand, it happens because we need to use variable for whole value of `filter` property, but is there way to now show this validation when at least part of the value contain variable like in my case?

**Comment by AndyOGo** [comment]
@acherkashin 
Variables as function parameters are not supported.
