### ISSUE TITLE
Stylelint v10 not included

### ISSUE THREAD

**Issue by Sebl29** [AndyOGo/stylelint-declaration-strict-value#37]
Hi,
could you please add version stylelint >=10? Is it just an outdated dependency description or are there known issues?
I just read above the readme and the issues-tab, but did not find any comment on that.

Today I received a tiny message from "npm audit" about issues in stylelint-versions < 10.

**Comment by AndyOGo** [comment]
@Sebl29 Thanks for your feedback.
I'm not aware of v10 issues, but haven't tested it myself - should be straight forward.

**Comment by Cherry** [comment]
We've been using this plugin with Stylelint v10 without any issues. There's a `stylelint-declaration-strict-value@1.1.2 requires a peer of stylelint@^7.0.0 || ^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.` warning, but it doesn't appear as if there are any issues.

**Comment by AndyOGo** [comment]
@Cherry 
@Sebl29 
Thanks for your feedback.

I just published `v1.1.3` with Stylint 10.
