### ISSUE TITLE
support stylelint@11

### ISSUE THREAD

**Issue by gussyboy** [AndyOGo/stylelint-declaration-strict-value#40]
Update to support stylelint version 11

**Comment by AndyOGo** [comment]
@gussyboy Thanks for your issue.
Can you please provide any error log, configuration, etc?

The official Changelog does not reveal any breaking changes for plugin development:
https://stylelint.io/changelog#1100

Or do mean to update the `peerDependencies`?
https://github.com/AndyOGo/stylelint-declaration-strict-value/blob/16ecf39f218441d9ac442cccaa36b4687c289e9f/package.json#L33-L35

**Comment by AndyOGo** [comment]
@gussyboy no worries, I just upgraded to stylelint v11, all tests still pass.
Will do a patch release...
