### ISSUE TITLE
TypeError: autoFixFuncNormalized is not a function

### ISSUE THREAD

**Issue by EvgenyOrekhov** [AndyOGo/stylelint-declaration-strict-value#44]
```text
TypeError: autoFixFuncNormalized is not a function
    at src/css/main.css:2:5
    at lintDeclStrictValue (node_modules/stylelint-declaration-strict-value/index.js:132:30)
    at node_modules/postcss/lib/container.js:198:18
    at node_modules/postcss/lib/container.js:135:18
    at Rule.each (node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (node_modules/postcss/lib/container.js:131:17)
    at node_modules/postcss/lib/container.js:148:24
    at Root.each (node_modules/postcss/lib/container.js:101:16)
    at Root.walk (node_modules/postcss/lib/container.js:131:17)
    at Root.walkDecls (node_modules/postcss/lib/container.js:196:19)
    at node_modules/stylelint-declaration-strict-value/index.js:74:12
```

main.css

```css
.foo {
    color: #000;
}
```

.stylelintrc.json

```json
{
    "plugins": [
        "stylelint-declaration-strict-value"
    ],

    "rules": {
        "scale-unlimited/declaration-strict-value": [
            "/color/",
            {
                "ignoreVariables": true,
                "ignoreFunctions": false,
                "ignoreKeywords": ["currentColor", "transparent", "inherit"]
            }
        ]
    }
}
```

stylelint version: 11.0.0
stylelint-declaration-strict-value: 1.1.6

**Comment by EvgenyOrekhov** [comment]
Command: `node_modules/.bin/stylelint src/css/main.css --fix`

**Comment by AndyOGo** [comment]
Hey @EvgenyOrekhov 
This plugin supports only dynamic autofixing, by proving a custom autofix function.
You can read more at the docs: https://github.com/AndyOGo/stylelint-declaration-strict-value#autofix-support

To handle this, either provide above function, or disable this, just set [`disableFix` option](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md#the-anatomy-of-a-plugin) to `true`
> If your plugin rule supports [autofixing](rules.md#adding-autofixing), then `ruleFunction` should also accept a third argument: context. Also, it's highly recommended to support the `disableFix` option in your secondary options object. Within the rule, don't perform autofixing if the user has passed a `disableFix` option for your rule.

**Comment by EvgenyOrekhov** [comment]
@AndyOGo I expect `disableFix` to be `true` by default if `autoFixFunc` is not provided.

**Comment by AndyOGo** [comment]
@EvgenyOrekhov 
I can see this expectation (I also though about in #18), though it would not align with the "anatomy of a plugin" as described here:
https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md#the-anatomy-of-a-plugin

**Comment by EvgenyOrekhov** [comment]
@AndyOGo The document you refer to doesn't say that `disableFix` cannot be `true` by default.

**Comment by AndyOGo** [comment]
Thanks for your feedback.
Though I think the documentation is very clear about it:
> Within the rule, **don't perform autofixing if the user has passed a disableFix option for your rule**.
