### ISSUE TITLE
The `/color/` regex produces false-positives

### ISSUE THREAD

**Issue by EvgenyOrekhov** [AndyOGo/stylelint-declaration-strict-value#76]
The README has `/color/` as an example regex, but it catches the following CSS properties:

- https://www.w3.org/TR/2020/WD-css-color-adjust-1-20200402/#propdef-color-adjust
- https://www.w3.org/TR/2018/WD-filter-effects-1-20181218/#propdef-color-interpolation-filters
- https://www.w3.org/TR/2020/WD-css-color-adjust-1-20200402/#propdef-color-scheme
- https://www.w3.org/TR/2020/WD-css-color-adjust-1-20200402/#propdef-forced-color-adjust

In most cases, you don't want to use variables with these properties, because they don't accept [`<color>`](https://www.w3.org/TR/css-color-4/#typedef-color) values.

I think the README should be updated to use `/color$/` instead of `/color/` as an example regex.

Regex test: https://regex101.com/r/C0riA2/1.

**Comment by AndyOGo** [comment]
Thank you @EvgenyOrekhov  for your feedback.

That's right, the readme should give best practise example.
Though it's expected, that the user is aware of the application and extent of regular expressions.

I will adapt the readme asap.

**Comment by AndyOGo** [comment]
@EvgenyOrekhov Release with [`v1.4.7`](https://github.com/AndyOGo/stylelint-declaration-strict-value/compare/v1.4.6...v1.4.7)
